### ISSUE TITLE
localhost does not work for the plugin ? 

### ISSUE THREAD

**Issue by judgement96** [cgkineo/adapt-launchNewWindow#8]
Hello I just started using adapt authoring tool a few days back. I have difficulty using the adapt new window launcher as i'm using localhost for now. Any details on how it works ?

**Comment by moloko** [comment]
@judgement96 when logging an issue, please could you supply as much of the following information as is relevant?

Equally if you have questions if you make them as specific as possible it'll make it easier for us to answer them

### Subject of the issue/enhancement/features
Describe your issue here.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots (if you can)
